### ISSUE TITLE
ReferenceError: setTimeout is not defined

### ISSUE THREAD

**Issue by unite4** [grrowl/homebridge-plugin-automation#3]
**Describe The Bug:**

When testing the examples provided in the project documentation, I encountered a problem with the operation of the `setTimeout` function, which is not available in the listener context.

**To Reproduce:**

Use following script:
```
automation.listen((event) => {
  setTimeout(function () {
    console.log('test', event)
  }, 100);
});
```

**Expected behavior:**

`setTimeout` timer is set properly.

**Logs:**

```
[4/21/2024, 7:39:08 PM] [HomebridgeAutomation] Error running Automation script: ReferenceError: setTimeout is not defined
```

**Plugin Config:**

**Screenshots:**

**Environment:**

* **Plugin Version**: 0.1.1
* **Homebridge Version**: 1.7.0
* **Node.js Version**: 18.19.0
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by grrowl** [comment]
Thank you for the report and using the plugin! Fixed :)
